#!/bin/bash
source /infra/utils

set -e
set +u

cd $TARGET

# add the app to omero.web.apps
value=$(get_app_name)

su - omero-web -c "env OMERODIR=$OMERODIR /opt/omero/web/venv3/bin/omero config set omero.web.apps '[\"$value\"]'"
