#!/bin/bash

set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

. ${dir}/utils
PROJECT=${PROJECT:-$(get_project_name)}
# Note: for backwards compatibility, we're not yet
# making use of COMPOSE_PROJECT_NAME

cd $dir
exec docker compose -p ${PROJECT} "$@"
