#!/bin/bash
source /infra/utils

set -u
set -x

TARGET=${TARGET:-..}

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd $TARGET

pip install --upgrade setuptools wheel
pip install --upgrade -r $dir/requirements.txt
