#!/bin/bash
source /infra/utils

set -e
set -u
set -x

TARGET=${TARGET:-..}
PLUGIN=${PLUGIN:-}

python --version
pip install https://github.com/glencoesoftware/zeroc-ice-py-linux-x86_64/releases/download/20231130/zeroc_ice-3.6.5-cp39-cp39-manylinux_2_28_x86_64.whl
pip install bftools

cd $TARGET
cd $(setup_dir)
pip install .
python setup.py clean
rm -rf dist *egg-info src/*egg-info
