#!/bin/bash

set -e
set -u

setup_dir() {
    # check the location of setup.py
    ref_file="setup.py"
    directory="./"
    values=()
    if [ ! -f $ref_file ]; then
        values=$(find "$(pwd -P)" -name $ref_file)
        if [ ${#values[@]} == 1 ]; then
            directory=$(dirname ${values[0]})
        fi
    fi
    echo $directory
}

get_app_name() {
    # convert the directory name into the app name
    echo $(echo $(basename $PWD) | tr - _)
}

get_project_name() {
   echo $(get_app_name | tr -cd '[[:alnum:]]' | tr /A-Z/ /a-z/)
}

if [ ! -z ${VIRTUAL_ENV:-} ]; then
    # see https://github.com/pypa/virtualenv/issues/1029
    PS=${PS:-}
    VIRTUAL_ENV_DISABLE_PROMPT=true source $VIRTUAL_ENV/bin/activate
fi
