#!/usr/bin/env python

import atexit
import omero
import os
import socket
import time


OMERO_DIST = os.environ.get("OMERO_DIST", "/opt/omero/server/OMERO.server")
if not os.path.exists(OMERO_DIST):
	OMERO_DIST = "/opt/omero/web/OMERO.web"

OMERO_HOST = os.environ.get("OMERO_HOST", "localhost")
OMERO_USER = os.environ.get("OMERO_USER", "root")
OMERO_PASS = os.environ.get("OMERO_PASS", "omero")
OMERO_PORT = int(os.environ.get("OMERO_PORT", "4064"))
SLEEP_TIME = int(os.environ.get("SLEEP_TIME", "30"))


def end():
    print("travis_fold:end:wait-on-login")

atexit.register(end)

print("travis_fold:start:wait-on-login")


def port_is_open():
    rc = socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect_ex((OMERO_HOST, OMERO_PORT))
    return (rc == 0)


for x in range(1, 31):
    if port_is_open():
        break
    else:
        time.sleep(1.0)
        print("waiting on port: #%s" % x)


# HACK: This 'ready' detection is still not working. Adding a hard sleep to be safe.
print("Sleeping for", SLEEP_TIME)
time.sleep(SLEEP_TIME)

# Second: try to login
for x in range(1, 6):
    # https://trello.com/c/rPstbt4z/216-open-ssl-110
    client = omero.client(OMERO_HOST, OMERO_PORT)
    try:
        client.createSession(OMERO_USER, OMERO_PASS)
        break
    except:
        print("Login attempt %s failed. Trying again in %s seconds" % (x, x+1))
        time.sleep(x+1)
    finally:
        client.__del__()
